### ISSUE TITLE
陕西与山西

### ISSUE THREAD

**Issue by tabeworks** [xieyezi/2019-nCoV-Virus#1]
感谢。Bug report: 在演示 http://xieyezi.com:9001/ 里， 下拉菜单点陕西出现的是山西地图。

**Comment by xieyezi** [comment]
@tabeworks 你好，谢谢反馈。会尽快修复这个bug

**Comment by xieyezi** [comment]
@tabeworks  此bug已在最新一次提交中修复！

**Comment by tabeworks** [comment]
非常感谢。有更新时长？目前点击下拉列表里的“陕西”，效果没有变化，显示的仍是山西地图。

**Comment by xieyezi** [comment]
@tabeworks 昨天晚上修复了，没部署到服务器，现在部署了，你再访问试试看。

**Comment by tabeworks** [comment]
@xieyezi 显示正常。牛~ 辛苦啦。
